using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using Aetherphone.Core.Aethernet.Contracts;
using Aetherphone.Core.Casino;
using Xunit;

namespace Aetherphone.Tests;

// The pinned vectors below were generated by hand-running the backend fairness recipe with an
// independent implementation (Python hashlib/hmac): streamKey = HMAC-SHA256(seed, utf8(roundId)),
// block t = HMAC-SHA256(streamKey, uint32BE(t)), big-endian 32-bit reads, and exact rejection
// sampling with limit = 2^32 / bound * bound. If the verifier drifts from the server recipe in
// endianness, counter width, or rejection math, these constants stop matching.
public sealed class CasinoVerifierTests
{
    private const string Seed = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
    private const string SeedCommit = "630dcd2966c4336691125448bbb25b4ff412a49c732db2c8abc1b8581bd710dd";
    private const string SlotsRoundId = "f00d4b1dfeedc0de1234567890abcdef";
    private const string SlotsLog = "s0r0:19;s0r1:22;s0r2:29;s0r3:33;s0r4:23";
    private const string ScratchRoundId = "cafe0000000000000000000000000002";
    private const string ScratchLog =
        "prize:757510;w0:4;w1:6;w2:2;w3:2;w4:7;w5:2;g8:1;g7:4;g6:4;g5:4;g4:4;g3:0;g2:0;g1:0";
    private const string BarkeepRoundId = "cafe0000000000000000000000000003";
    private const string BarkeepLog = "patrons:7;a0:0;n0:0;k0.0:2;k0.1:1;a1:2;n1:2;k1.0:2;k1.1:0";
    private const string WheelRoundId = "cafe0000000000000000000000000004";
    private const string WheelLog = "segment:16";
    private const string SpinRoundId = "cafe0000000000000000000000000005";
    private const string SpinLog = "segment:6";
    private const string BingoRoundId = "cafe0000000000000000000000000006";
    private const string BingoLog =
        "card:2;card:8;card:5;card:1;card:6;card:7;card:0;card:12;card:6;card:6;card:4;card:7;card:2;card:9;"
        + "card:7;card:11;card:6;card:9;card:2;card:9;card:13;card:12;card:5;card:7;"
        + "ball:55;ball:3;ball:55;ball:57";
    private const string BingoTwoCardLog =
        "card:2;card:8;card:5;card:1;card:6;card:7;card:0;card:12;card:6;card:6;card:4;card:7;card:2;card:9;"
        + "card:7;card:11;card:6;card:9;card:2;card:9;card:13;card:12;card:5;card:7;"
        + "card:10;card:1;card:7;card:9;card:2;card:13;card:5;card:11;card:0;card:3;card:10;card:1;card:7;"
        + "card:6;card:1;card:10;card:5;card:11;card:8;card:10;card:2;card:2;card:8;card:7";

    [Fact]
    public void SlotsVectorReproducesTheCommitAndEveryDraw()
    {
        Assert.Equal(CasinoRoundVerdict.Match,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, Seed, SeedCommit, SlotsRoundId, SlotsLog));
    }

    [Fact]
    public void ScratchWinnerVectorReplays()
    {
        Assert.Equal(CasinoRoundVerdict.Match,
            CasinoVerifier.Verify(CasinoWire.ScratchKind, Seed, SeedCommit, ScratchRoundId, ScratchLog));
    }

    [Fact]
    public void BarkeepScriptVectorReplays()
    {
        Assert.Equal(CasinoRoundVerdict.Match,
            CasinoVerifier.Verify(CasinoWire.BartenderKind, Seed, SeedCommit, BarkeepRoundId, BarkeepLog));
    }

    [Fact]
    public void WheelSegmentVectorReplays()
    {
        Assert.Equal(CasinoRoundVerdict.Match,
            CasinoVerifier.Verify(CasinoWire.WheelKind, Seed, SeedCommit, WheelRoundId, WheelLog));
    }

    [Fact]
    public void DailySpinVectorReplays()
    {
        Assert.Equal(CasinoRoundVerdict.Match,
            CasinoVerifier.Verify(CasinoWire.DailySpinKind, Seed, SeedCommit, SpinRoundId, SpinLog));
    }

    // The two bingo shuffles narrow as they go and the engine logs both under one name apiece, so
    // the replay has to count how many draws of each purpose it has already spent. A card is
    // twenty four picks out of a shrinking column pool; the tumbler counts down from seventy five.
    [Fact]
    public void BingoCardAndBallVectorReplays()
    {
        Assert.Equal(CasinoRoundVerdict.Match,
            CasinoVerifier.Verify(CasinoWire.BingoKind, Seed, SeedCommit, BingoRoundId, BingoLog));
    }

    [Fact]
    public void ASecondCardRestartsTheColumnPoolPattern()
    {
        Assert.Equal(CasinoRoundVerdict.Match,
            CasinoVerifier.Verify(CasinoWire.BingoKind, Seed, SeedCommit, BingoRoundId, BingoTwoCardLog));
    }

    [Fact]
    public void ABingoDrawAtItsNarrowedBoundFails()
    {
        const string tampered = "card:2;card:8;card:5;card:1;card:11";
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.BingoKind, Seed, SeedCommit, BingoRoundId, tampered));
    }

    [Fact]
    public void TestLocalReferenceAgreesWithThePinnedVector()
    {
        var reference = ReferenceLog(Seed, SlotsRoundId);
        Assert.Equal(SlotsLog, reference);
    }

    [Fact]
    public void TamperedSeedFailsTheCommitCheck()
    {
        var tampered = string.Concat(Seed.AsSpan(0, Seed.Length - 1), "0");
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, tampered, SeedCommit, SlotsRoundId, SlotsLog));
    }

    [Fact]
    public void TamperedSeedWithItsOwnCommitStillFailsTheDrawReplay()
    {
        var tampered = string.Concat("ff", Seed.AsSpan(2));
        var tamperedCommit = Convert.ToHexStringLower(SHA256.HashData(Convert.FromHexString(tampered)));
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, tampered, tamperedCommit, SlotsRoundId, SlotsLog));
    }

    [Fact]
    public void TheStreamIsBoundToTheRoundId()
    {
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, Seed, SeedCommit, ScratchRoundId, SlotsLog));
    }

    [Fact]
    public void ATamperedDrawValueFails()
    {
        const string tamperedLog = "s0r0:20;s0r1:22;s0r2:29;s0r3:33;s0r4:23";
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, Seed, SeedCommit, SlotsRoundId, tamperedLog));
    }

    [Fact]
    public void AnUnknownPurposeFailsClosed()
    {
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, Seed, SeedCommit, SlotsRoundId, "mystery:1"));
    }

    [Fact]
    public void AValueAtOrAboveItsBoundFails()
    {
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, Seed, SeedCommit, SlotsRoundId, "s0r0:40"));
    }

    [Fact]
    public void AMalformedSeedIsAMismatchNotACrash()
    {
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, "not-hex", SeedCommit, SlotsRoundId, SlotsLog));
    }

    // Commit evidence alone says a seed was published, never that this round came out of it. A
    // server that reveals a seed and logs no draws must not collect the strongest verdict, so
    // the missing evidence fails closed rather than open.
    [Fact]
    public void AnEmptyDrawLogFailsClosedInsteadOfPassingOnTheCommitAlone()
    {
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, Seed, SeedCommit, SlotsRoundId, string.Empty));
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.SlotsKind, Seed, "00" + SeedCommit[2..], SlotsRoundId, string.Empty));
    }

    [Fact]
    public void ASettledDtoWithoutADrawLogIsAMismatchNotAMatch()
    {
        var evidenceless = new CasinoRoundVerifyDto(
            Granted: true,
            RoundId: SlotsRoundId,
            GameKind: "casino.slots",
            State: CasinoRoundStates.Settled,
            SeedCommitHash: SeedCommit,
            SeedRevealed: Seed,
            DrawLog: "");
        Assert.Equal(CasinoRoundVerdict.Mismatch, CasinoVerifier.Verify(evidenceless));
    }

    [Fact]
    public void AnOpenRoundStaysUnrevealed()
    {
        var open = new CasinoRoundVerifyDto(
            Granted: false,
            Reason: "round_open",
            RoundId: BarkeepRoundId,
            GameKind: "casino.bartender",
            State: CasinoRoundStates.Open,
            SeedCommitHash: SeedCommit);
        Assert.Equal(CasinoRoundVerdict.Unrevealed, CasinoVerifier.Verify(open));
    }

    [Fact]
    public void ASettledRoundWithoutARevealedSeedStaysUnrevealed()
    {
        var sealedRound = new CasinoRoundVerifyDto(
            Granted: true,
            RoundId: SlotsRoundId,
            GameKind: "casino.slots",
            State: CasinoRoundStates.Settled,
            SeedCommitHash: SeedCommit,
            SeedRevealed: "");
        Assert.Equal(CasinoRoundVerdict.Unrevealed, CasinoVerifier.Verify(sealedRound));
    }

    [Fact]
    public void ASettledDtoWithTheVectorMatches()
    {
        var settled = new CasinoRoundVerifyDto(
            Granted: true,
            RoundId: SlotsRoundId,
            GameKind: "casino.slots",
            State: CasinoRoundStates.Settled,
            Stake: 5,
            Payout: 10,
            SeedCommitHash: SeedCommit,
            SeedRevealed: Seed,
            NextSeedHash: SeedCommit,
            DrawLog: SlotsLog);
        Assert.Equal(CasinoRoundVerdict.Match, CasinoVerifier.Verify(settled));
    }

    [Fact]
    public void PurposeBoundsMirrorTheEngines()
    {
        Assert.True(CasinoVerifier.TryBoundFor("s0r0", 0u, out var slotsBound));
        Assert.Equal(40u, slotsBound);
        Assert.True(CasinoVerifier.TryBoundFor("prize", 0u, out var prizeBound));
        Assert.Equal(1_000_000u, prizeBound);
        Assert.True(CasinoVerifier.TryBoundFor("w0", 0u, out var winnerBound));
        Assert.Equal(12u, winnerBound);
        Assert.True(CasinoVerifier.TryBoundFor("w5", 0u, out var lastWinnerBound));
        Assert.Equal(7u, lastWinnerBound);
        Assert.True(CasinoVerifier.TryBoundFor("g8", 0u, out var shuffleBound));
        Assert.Equal(9u, shuffleBound);
        Assert.True(CasinoVerifier.TryBoundFor("l0", 0u, out var loserBound));
        Assert.Equal(14u, loserBound);
        Assert.True(CasinoVerifier.TryBoundFor("patrons", 0u, out var patronsBound));
        Assert.Equal(16u, patronsBound);
        Assert.True(CasinoVerifier.TryBoundFor("a3", 0u, out var jitterBound));
        Assert.Equal(3u, jitterBound);
        Assert.True(CasinoVerifier.TryBoundFor("n11", 0u, out var stepCountBound));
        Assert.Equal(3u, stepCountBound);
        Assert.True(CasinoVerifier.TryBoundFor("k13.3", 0u, out var stepKindBound));
        Assert.Equal(4u, stepKindBound);
        Assert.False(CasinoVerifier.TryBoundFor("w6", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("g0", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("g9", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("l9", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("a14", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("k14.0", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("k0.4", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("s41r0", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("s0r5", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("", 0u, out _));
    }

    // Both wheels log their draw under the one name "segment" and they are different wheels, so
    // the bound arrives from the round's game kind rather than the label. Reading a sixteen
    // segment draw against a fifty segment bound consumes the stream differently, which would
    // accuse the house of cheating on every honest daily spin.
    [Fact]
    public void TheCommunalPurposeBoundsMirrorTheirRules()
    {
        Assert.True(CasinoVerifier.TrySegmentBound(CasinoWire.WheelKind, out var wheelSegments));
        Assert.Equal(50u, wheelSegments);
        Assert.True(CasinoVerifier.TrySegmentBound(CasinoWire.DailySpinKind, out var spinSegments));
        Assert.Equal(16u, spinSegments);

        Assert.True(CasinoVerifier.TryBoundFor("segment", wheelSegments, out var segmentBound));
        Assert.Equal(50u, segmentBound);
        Assert.True(CasinoVerifier.TryBoundFor("segment", spinSegments, out var spinBound));
        Assert.Equal(16u, spinBound);

        Assert.True(CasinoVerifier.TryBoundFor("card", 0, 0u, out var firstPick));
        Assert.Equal(15u, firstPick);
        Assert.True(CasinoVerifier.TryBoundFor("card", 4, 0u, out var lastPick));
        Assert.Equal(11u, lastPick);
        Assert.True(CasinoVerifier.TryBoundFor("card", 13, 0u, out var middleColumnLastPick));
        Assert.Equal(12u, middleColumnLastPick);
        Assert.True(CasinoVerifier.TryBoundFor("card", 24, 0u, out var secondCardFirstPick));
        Assert.Equal(15u, secondCardFirstPick);

        Assert.True(CasinoVerifier.TryBoundFor("ball", 0, 0u, out var firstBall));
        Assert.Equal(75u, firstBall);
        Assert.True(CasinoVerifier.TryBoundFor("ball", 73, 0u, out var lastBall));
        Assert.Equal(2u, lastBall);
    }

    // Guessing one of the two rims would hand a round the strongest verdict on a coin flip, so a
    // game kind this client does not know leaves the segment bound at zero and every draw under
    // it fails closed.
    [Fact]
    public void AWheelThisClientDoesNotKnowFailsClosedRatherThanGuessing()
    {
        Assert.False(CasinoVerifier.TrySegmentBound(CasinoWire.BingoKind, out var bingoSegments));
        Assert.Equal(0u, bingoSegments);
        Assert.False(CasinoVerifier.TrySegmentBound("casino.mystery", out _));
        Assert.False(CasinoVerifier.TryBoundFor("segment", 0u, out _));

        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify("casino.mystery", Seed, SeedCommit, WheelRoundId, WheelLog));
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.DailySpinKind, Seed, SeedCommit, WheelRoundId, WheelLog));
    }

    // A shuffle that ran past its own end has no honest bound left, and a purpose the client has
    // never heard of has none either. Both are mismatches, never a shrug that passes.
    [Fact]
    public void AShuffleRunPastItsEndFailsClosedLikeAnUnknownPurpose()
    {
        Assert.False(CasinoVerifier.TryBoundFor("ball", 74, 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("ball", 900, 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("card", -1, 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("balls", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("cards", 0u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("segments", 50u, out _));
        Assert.False(CasinoVerifier.TryBoundFor("spins", 16u, out _));
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.BingoKind, Seed, SeedCommit, BingoRoundId, "wedge:3"));
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.DailySpinKind, Seed, SeedCommit, SpinRoundId, "segment:16"));
        Assert.Equal(CasinoRoundVerdict.Mismatch,
            CasinoVerifier.Verify(CasinoWire.WheelKind, Seed, SeedCommit, WheelRoundId, "segment:50"));
    }

    private static string ReferenceLog(string seedHex, string roundId)
    {
        var seed = Convert.FromHexString(seedHex);
        var streamKey = new HMACSHA256(seed).ComputeHash(Encoding.UTF8.GetBytes(roundId));
        using var blockHasher = new HMACSHA256(streamKey);
        var words = new List<uint>();
        for (uint blockCounter = 0; words.Count < 32; blockCounter++)
        {
            var counterBytes = new byte[4];
            BinaryPrimitives.WriteUInt32BigEndian(counterBytes, blockCounter);
            var block = blockHasher.ComputeHash(counterBytes);
            for (var wordIndex = 0; wordIndex < block.Length; wordIndex += 4)
            {
                words.Add(BinaryPrimitives.ReadUInt32BigEndian(block.AsSpan(wordIndex, 4)));
            }
        }

        var builder = new StringBuilder();
        var readIndex = 0;
        for (var reel = 0; reel < 5; reel++)
        {
            const uint bound = 40;
            const ulong limit = 0x1_0000_0000UL / bound * bound;
            uint raw;
            do
            {
                raw = words[readIndex];
                readIndex++;
            }
            while (raw >= limit);

            if (builder.Length > 0)
            {
                builder.Append(';');
            }

            builder.Append("s0r").Append(reel).Append(':').Append(raw % bound);
        }

        return builder.ToString();
    }
}
